### ISSUE TITLE
Missing default value on slider control for Vote Issuance and Mint Fee questions

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#10]
20/7/22 freeosgov2 Frontend v0.1.5 verovera
When completing the Vote questionnaire, the default value which is the middle of the range is missing from both the Vote Issuance and Mint Fee questions.
Also missing % signs on the slider control and manually entered amount for all the voting questions.

![Freeos App 20-07-2022 15-31-08](https://user-images.githubusercontent.com/77765830/179894761-55a14812-9d83-411f-8b07-5b0c3dcee303.png)
![Freeos App 20-07-2022 16-21-12](https://user-images.githubusercontent.com/77765830/179896190-8dd536b3-b9a1-4214-8a16-364551f47441.png)

**Comment by judytan21** [comment]
26/7/22 Retest. freeosgov2 frontend v0.1.6. Still the same. Not fixed.

**Comment by stuartmcphersonflipmind** [comment]
I think we will leave this off MVP unless I get some free time at the end

**Comment by conorseed** [comment]
Fixed in v0.1.16

**Comment by judytan21** [comment]
3/8/22 Retest. freeosgov2 frontend v0.1.16 account: verovera Link: https://twilight-cloud-0240.on.fleek.co/#/activities. Partially Fixed. Almost there Conor...missing % signs on the default values and manually entered amount for all the voting questions.
Dave's UX
<img width="458" alt="Screen Shot 2022-08-03 at 4 34 21 PM" src="https://user-images.githubusercontent.com/77765830/182525437-5dc2893c-4a0f-4be0-a90e-8bc58609c86b.png">
freeosgov2
<img width="458" alt="Screen Shot 2022-08-03 at 4 36 13 PM" src="https://user-images.githubusercontent.com/77765830/182525459-a954fe2c-d380-41bf-afeb-f306da2da94f.png">

**Comment by judytan21** [comment]
@conorseed Good enough for MVP. Will keep it open in case you wanna fix it.

**Comment by conorseed** [comment]
@judytan21 Ahhh I didn't realise those needed fixing too! 
I've had another play and pushed some changes for this in v0.1.17. 
Hopefully closer to the mark :)

**Comment by judytan21** [comment]
8/8/22 freeosgov2 frontend v0.1.17. Fixed
![Freeos App 08-08-2022 11-44-05](https://user-images.githubusercontent.com/77765830/183315756-675f0922-d135-4ebd-b0a0-da9dab4efa41.png)
![Freeos App 08-08-2022 11-44-21](https://user-images.githubusercontent.com/77765830/183315759-3f83c4c2-a1d0-4edf-b34c-31f01a180d20.png)
.
