### ISSUE TITLE
Unregistered KYCed user was not taken to 'Registration' page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#6]
20/7/22 Governance Frontend v0.1.4
Login as vincentvegan, KYCed (kyc record in freeosconfig userinfo table) but not registered (no Participant record).  
Was presented with the 'Sorry You are Not Verified yet' page. Expecting to be taken to 'Registration' page
![Freeos App 20-07-2022 11-23-46](https://user-images.githubusercontent.com/77765830/179865515-7a1100a1-b2b7-4b5c-a713-caa2b39f928e.png)
.

**Comment by sjmcpherson** [comment]
I can't see a entry in the Wallet Keys Spreadsheet for vincentvegan but maybe your not looking at the correct Contract should be freeosgov2 rather than freeosconfig

**Comment by judytan21** [comment]
You can find him in the Wallets keys spreadsheet, Verification sheet. Verified users will have an entry in the freeosconfig userinfo table.

**Comment by sjmcpherson** [comment]
OK thanx found him, vincentvegan doesnt have a KYC record and therefore is coming up a "E" user

**Comment by judytan21** [comment]
He is kyced as his kyc details are in the freeosconfig userinfo table.

**Comment by judytan21** [comment]
Which table are you using for kyc status?
In production:VERIFICATION_CONTRACT = "eosio.proton"
In development: VERIFICATION_CONTRACT = "freeosconfig"

**Comment by sjmcpherson** [comment]
Ah yes nice catch that field was previously coming from the Parameters table, Ive changed it to be enviroment variable for Tom to change fixed in v0.1.5

**Comment by judytan21** [comment]
26/7/22 Retest. freeosgov2 frontend v0.1.6. After login as vincentvegan (verified but not registered), was returned to Connect Wallet page. Not fixed.

**Comment by judytan21** [comment]
27/7/22 Retest. freeosgov2 frontend v0.1.7. After login as vincentvegan (verified but not registered), was taken to 'Registration' page which is correct.Fixed
![Freeos App 27-07-2022 14-55-29](https://user-images.githubusercontent.com/77765830/181151103-37431151-06fe-4201-9e10-f745348fb30d.png)
.
