### ISSUE TITLE
Alpha test: Assertion error minting Airclaim allowance to BETA

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/freeosgov_frontend#90]
Despite having a large enough balance I get an assert error:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/18106735/194428587-cd4ffc76-df38-4e44-8cd8-2cd260746c22.png">

**Comment by tommccann777** [comment]
Fixed in version 0.9.60 of the freeosgov contract deployed to alphaclaim. Ready for re-test.

**Comment by judytan21** [comment]
10/10/22 Retest. Mint 7394.2936 POINTs to FREEOS (Beta) for tomalpha. Still getting error "You do not have enough to complete the transaction". Not fixed.
![Freeos Governance dApp 10-10-2022 10-57-26](https://user-images.githubusercontent.com/77765830/194781373-a3c55f25-3297-45c7-97de-4f7f527aa341.png)

**Comment by tommccann777** [comment]
The figures are correct. Please re-test

**Comment by judytan21** [comment]
26/10/22 Tom confirmed this is now working. Closing issue.
